export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const TEXTADD = "TEXTADD";
export const TEXTSUB = "TEXTSUB";
export const INCREMENT_BY_VALUE = "INCREMENTEBYVALUE";
export const DECREMENT_BY_VALUE = "DECREMENTEBYVALUE";
